name: caveau
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: https://github.com/stiavelli21/Caveau.git

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.3.1
  local_auth: ^3.0.1
  provider: ^6.1.5+1
  crypto: ^3.0.7
  pointycastle: ^3.9.1
  uuid: ^4.6.0
  intl: ^0.20.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/caveau_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0B0F19"
  adaptive_icon_foreground: "assets/icons/caveau_adaptive_foreground.png"
  web:
    generate: true
    image_path: "assets/icons/caveau_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/caveau_icon.png"
